name: First Workflow

on:
  push:
    branches:
      - main   # only run on pushes to main branch (optional)

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a string
        run: echo "hello world"

      - name: Check Node and NPM versions
        run: |
          node -v
          npm -v
  parallel-job-macos:                                                                                                                                              
    runs-on: macos-latest    
    steps:
      - name: View SW Version
        run: sw_vers
        
  dependent-job:
    runs-on: windows-latest
    needs: run-shell-commands
    steps:
        - name: echo a string
          run: Write-Output "Windows String"
        - name: Error Step
          run: doesnotexits  



