name: First Workflow

on:
  push:
    branches:
      - main

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a string
        run: echo "hello world"

      - name: Check Node and NPM versions
        run: |
          node -v
          npm -v

  parallel-job-macos:                                                                                                                                              
    runs-on: macos-latest    
    steps:
      - name: View macOS version
        run: sw_vers   # correct command on macOS (not sw_version)

  dependent-job:
    runs-on: windows-latest
    needs: run-shell-commands
    steps:
      - name: Echo a string
        run: Write-Output "Windows String"

      - name: Error Step (optional)
        run: doesnotexits
        continue-on-error: true   # <-- prevents workflow failure
